# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env: 
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
    # Checkout the code
    - uses: actions/checkout@v4

    # Setup Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Navigate to the server directory and install dependencies
    - name: Install dependencies
      working-directory: server
      run: npm ci

    # Build the source code (if applicable)
    - name: Build project
      working-directory: server
      run: npm run build --if-present

    # Run tests
    - name: Run tests
      working-directory: server
      run: npm test -- --exit
